In [1]:
import numpy as np
import pandas as pd

In [3]:
k = [90,20,3,4,90,23]
dt = pd.DataFrame(k)
print(dt)
dt

    0
0  90
1  20
2   3
3   4
4  90
5  23

    0
0  90
1  20
2   3
3   4
4  90
5  23

In [7]:
k = [(19,20,21),(10,20,30)]
dt = pd.DataFrame(k, columns = ('m1','m2','m3')) # atribute/property
print(dt)

   m1  m2  m3
0  19  20  21
1  10  20  30

In [8]:
w = [['sun','mon','tue'],['jan', 'feb','mar']]
dt = pd.DataFrame(w)
print(dt)

     0    1    2
0  sun  mon  tue
1  jan  feb  mar

In [10]:
arr = np.array(w)
arr

array([['sun', 'mon', 'tue'],
       ['jan', 'feb', 'mar']], dtype='<U3')

In [11]:
tr = arr.T
tr

array([['sun', 'jan'],
       ['mon', 'feb'],
       ['tue', 'mar']], dtype='<U3')

In [13]:
dt = pd.DataFrame(tr, columns = ['week','month'])
print(dt)

  week month
0  sun   jan
1  mon   feb
2  tue   mar

In [14]:
w = {'Weekdays':['sun','mon','tue'],'Months':['jan', 'feb','mar']}
dt = pd.DataFrame(w)
dt

  Weekdays Months
0      sun    jan
1      mon    feb
2      tue    mar

In [18]:
w = np.array([['sun','mon','tue'],['jan', 'feb','mar']]).reshape(3,2)
dt = pd.DataFrame(w)
dt

     0    1
0  sun  mon
1  tue  jan
2  feb  mar

In [37]:
W = {'Rollno':[10,11,12,13,14],'Marks':[89,70,67,90,82],'Name':['Ankit','Amit','sumit','raman','harsh']}
dt = pd.DataFrame(W)
print(dt)

   Rollno  Marks   Name
0      10     89  Ankit
1      11     70   Amit
2      12     67  sumit
3      13     90  raman
4      14     82  harsh

In [22]:
dt.shape  # shape will return rows and columns

(5, 2)

In [24]:
print(dt.dtypes)

Rollno    int64
Marks     int64
dtype: object

In [25]:
print(dt.columns)

Index(['Rollno', 'Marks'], dtype='object')

In [27]:
print(dt.index)

RangeIndex(start=0, stop=5, step=1)

In [28]:
print(dt.values)

[[10 89]
 [11 70]
 [12 67]
 [13 90]
 [14 82]]

In [30]:
print(dt.head(2))

   Rollno  Marks
0      10     89
1      11     70

In [31]:
print(dt.tail(3))

   Rollno  Marks
2      12     67
3      13     90
4      14     82

In [39]:
print(dt.sample)

<bound method NDFrame.sample of    Rollno  Marks   Name
0      10     89  Ankit
1      11     70   Amit
2      12     67  sumit
3      13     90  raman
4      14     82  harsh>

In [38]:
print(dt.describe())

          Rollno      Marks
count   5.000000   5.000000
mean   12.000000  79.600000
std     1.581139  10.644247
min    10.000000  67.000000
25%    11.000000  70.000000
50%    12.000000  82.000000
75%    13.000000  89.000000
max    14.000000  90.000000

In [40]:
print(dt['Name'].describe())

count         5
unique        5
top       Ankit
freq          1
Name: Name, dtype: object

In [42]:
print(dt.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rollno  5 non-null      int64
 1   Marks   5 non-null      int64
 2   Name    5 non-null      object
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes
None

In [49]:
W = {'Rollno':[10,11,12,13,14],'Marks':[89,None,None,90,82],'Name':['Ankit','Ankit','sumit','raman','harsh']}
dt = pd.DataFrame(W)
print(dt)

   Rollno  Marks   Name
0      10   89.0  Ankit
1      11    NaN  Ankit
2      12    NaN  sumit
3      13   90.0  raman
4      14   82.0  harsh

In [44]:
print(dt.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rollno  5 non-null      int64
 1   Marks   3 non-null      float64
 2   Name    5 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes
None

In [45]:
print(dt.isnull())

   Rollno  Marks   Name
0   False  False  False
1   False   True  False
2   False   True  False
3   False  False  False
4   False  False  False

In [46]:
print(dt.isnull().sum())

Rollno    0
Marks     2
Name      0
dtype: int64

In [48]:
print(dt.duplicated())
print(dt.duplicated().sum())

0    False
1    False
2    False
3    False
4    False
dtype: bool
0

In [50]:
print(dt.duplicated())  #required entire row duplicate

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [51]:
W = {'Rollno':[10,11,12,13,10],'Marks':[89,None,None,90,89],'Name':['Ankit','Ankit','sumit','raman','Ankit']}
dt = pd.DataFrame(W)
print(dt)

   Rollno  Marks   Name
0      10   89.0  Ankit
1      11    NaN  Ankit
2      12    NaN  sumit
3      13   90.0  raman
4      10   89.0  Ankit

In [52]:
print(dt.duplicated().sum())

1