In [3]:
import pandas as pd
import numpy as np

In [4]:
data = {
    'math':[85,92,np.nan, 78],
    'science':[88,np.nan,91,84],
    'English':[np.nan,75,89,95]
}
df = pd.DataFrame(data)
missing = df.isnull()
display(missing)

    math  science  English
0  False    False     True
1  False     True    False
2   True    False    False
3  False    False    False

In [5]:
# filtering all rows with missing values
students = pd.DataFrame(
    {
        'Name':['Ashish','Rakhi','Dhun','Nitin'],
        'Gender':['M',None,"F",None]
    }
)
missing_gender = students[students['Gender'].isnull()]
print(missing_gender)

    Name Gender
1  Rakhi   None
3  Nitin   None

In [6]:
# using isna
# detecting missing values using isna()

data = {
    'student':['Ajay','Ravi',np.nan,'Suraj'],
    'Score':[90,np.nan,85,88]
}
df = pd.DataFrame(data)
print(df.isna())

   student  Score
0    False  False
1    False   True
2     True  False
3    False  False

In [7]:
# filling missing value using fillna()
df_filled = df.fillna(0)
print(df_filled)

  student  Score
0    Ajay   90.0
1    Ravi    0.0
2       0   85.0
3   Suraj   88.0

In [14]:
# using forward  fill (uss previous values)
df_fffill = df.fillna(method = 'ffill')
print(df_fffill)
df_fffill

  student  Score
0    Ajay   90.0
1    Ravi   90.0
2    Ravi   85.0
3   Suraj   88.0

C:\Users\Asus\AppData\Local\Temp\ipykernel_35792\1438246889.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_fffill = df.fillna(method = 'ffill')

  student  Score
0    Ajay   90.0
1    Ravi   90.0
2    Ravi   85.0
3   Suraj   88.0

In [16]:
# Backward fill 
df_bfill = df.fillna(method = 'bfill')
print(df_bfill)
df_bfill

  student  Score
0    Ajay   90.0
1    Ravi   85.0
2   Suraj   85.0
3   Suraj   88.0

C:\Users\Asus\AppData\Local\Temp\ipykernel_35792\2609214171.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill = df.fillna(method = 'bfill')

  student  Score
0    Ajay   90.0
1    Ravi   85.0
2   Suraj   85.0
3   Suraj   88.0

In [22]:
# Specific value Fill

data = {
    'student':['Ajay','Ravi',np.nan,'Suraj'],
    'Score':[90,np.nan,85,88]
}
df = pd.DataFrame(data)

In [24]:
fillspecific = df['Score'].fillna('unknown')
print(fillspecific)

0       90.0
1    unknown
2       85.0
3       88.0
Name: Score, dtype: object

In [25]:
# Replace value with replace() function
df_replace = df.replace(to_replace = np.nan, value = -1)
print(df_replace)

  student  Score
0    Ajay   90.0
1    Ravi   -1.0
2      -1   85.0
3   Suraj   88.0

In [26]:
# Using replace interpolate
data = {
    'A': [10,5,8,None,3],
    "B":[None, 7,15,9,None],
    "C":[12,11,None,6,4]
}
df = pd.DataFrame(data)

In [28]:
df_interpolate = df.interpolate(method = 'linear', limit_direction = 'forward')
print(df_interpolate)

      A     B     C
0  10.0   NaN  12.0
1   5.0   7.0  11.0
2   8.0  15.0   8.5
3   5.5   9.0   6.0
4   3.0   9.0   4.0

In [30]:
# strings Handling or manipulation
import pandas as pd
import numpy as np

In [32]:
data = {
    'Employee':['Rajesh', 'Shubham', 'Ashish', 'Neha', 'Mehak', np.nan, 'Prashant'],
    'Department': ['HR','Finance', 'IT', 'HR', 'Marketing', 'IT','Finance']
    
}
df = pd.DataFrame(data)
df

   Employee Department
0    Rajesh         HR
1   Shubham    Finance
2    Ashish         IT
3      Neha         HR
4     Mehak  Marketing
5       NaN         IT
6  Prashant    Finance