In [8]:
import pandas as pd
import numpy as np

In [9]:
# cleaning wrong format
my_data = pd.DataFrame({
    "Name": ["Alice","Bob","Charlie","David","Eva" , "Frank", "Grace", "Heide"],
    "Score": [85,np.nan,95,70,np.nan,88,95,88],
    "Age": [25,-1,23,22,21,25,np.nan,25],
    "Date" : ['2023-01-01','2023-02-15','not-a-date','2023-03-20','','2023-05-30','2023-05-30','2023-05-30']
})

In [10]:
df = pd.read_csv('my_data.csv')
df['Date'] = pd.to_datetime(df['Date'], errors = 'coerce')
print(df)
# in this code wrong format of date show as NaT (not a time)

      Name  Score   Age       Date
0    Alice   85.0  25.0 2023-01-01
1      Bob    NaN  -1.0 2023-02-15
2  Charlie   95.0  23.0        NaT
3    David   70.0  22.0 2023-03-20
4      Eva    NaN  21.0        NaT
5    Frank   88.0  25.0 2023-05-30
6    Grace   95.0   NaN 2023-05-30
7    Heide   88.0  25.0 2023-05-30

In [13]:
# removing column with wrong age format

df  = pd.read_csv('my_data.csv')
df = df[df['Age'] > 0 ]
df

      Name  Score   Age        Date
0    Alice   85.0  25.0  2023-01-01
2  Charlie   95.0  23.0  not-a-date
3    David   70.0  22.0  2023-03-20
4      Eva    NaN  21.0         NaN
5    Frank   88.0  25.0  2023-05-30
7    Heide   88.0  25.0  2023-05-30

In [15]:
# remove duplicate rows
df = pd.read_csv('my_data.csv')
df.drop_duplicates(inplace = True)
df

      Name  Score   Age        Date
0    Alice   85.0  25.0  2023-01-01
1      Bob    NaN  -1.0  2023-02-15
2  Charlie   95.0  23.0  not-a-date
3    David   70.0  22.0  2023-03-20
4      Eva    NaN  21.0         NaN
5    Frank   88.0  25.0  2023-05-30
6    Grace   95.0   NaN  2023-05-30
7    Heide   88.0  25.0  2023-05-30

In [ ]:
# DataSlicing and selection

In [16]:
# working with columns
import pandas as pd

In [17]:
data = {
    'Book':['1984','To Kill a mockingbird', 'The great gatspby', 'moby dick'],
    'Author':['George Orwell', 'Harper Lee', 'F.scott', 'Herman Melville'],
    'Genre':['Dystoppian','Classic','Classic','Adventure' ],
    'Price':[250,300,200,350]
}

df = pd.DataFrame(data)
df

                    Book           Author       Genre  Price
0                   1984    George Orwell  Dystoppian    250
1  To Kill a mockingbird       Harper Lee     Classic    300
2      The great gatspby          F.scott     Classic    200
3              moby dick  Herman Melville   Adventure    350

In [20]:
# selecting column
df[['Book','Price']]

                    Book  Price
0                   1984    250
1  To Kill a mockingbird    300
2      The great gatspby    200
3              moby dick    350

In [21]:
# adding column
publication_year = [1949,1960,1929,1851]
df['year'] = publication_year
df

                    Book           Author       Genre  Price  year
0                   1984    George Orwell  Dystoppian    250  1949
1  To Kill a mockingbird       Harper Lee     Classic    300  1960
2      The great gatspby          F.scott     Classic    200  1929
3              moby dick  Herman Melville   Adventure    350  1851

In [26]:
# deleting column
df.drop(['Genre'], axis = 1, inplace = True)
display(df)

KeyError: "['Genre'] not found in axis"

In [30]:
# selecting rows
row = df.loc[df['Book'] == 'moby dick']
row

        Book           Author  Price  year
3  moby dick  Herman Melville    350  1851

In [29]:
df

                    Book           Author  Price  year
0                   1984    George Orwell    250  1949
1  To Kill a mockingbird       Harper Lee    300  1960
2      The great gatspby          F.scott    200  1929
3              moby dick  Herman Melville    350  1851

In [33]:
# Selecting rows
rows = df.loc[df['Book'].isin(['moby dick', 'The Great gatspy'])]
rows

        Book           Author  Price  year
3  moby dick  Herman Melville    350  1851

In [37]:
# Adding Rows
new_book = pd.DataFrame({
    'Book': ['Pride and Prejudice'],
    'Author': ['Jane Austen'],
    'Price' : [200],
    'Year': [1813]
})

df = pd.concat([df,new_book], ignore_index = True)
df

                    Book           Author  Price    year    Year
0                   1984    George Orwell    250  1949.0     NaN
1  To Kill a mockingbird       Harper Lee    300  1960.0     NaN
2      The great gatspby          F.scott    200  1929.0     NaN
3              moby dick  Herman Melville    350  1851.0     NaN
4    Pride and Prejudice      Jane Austen    200     NaN  1813.0

In [38]:
# deleting rows
df = df[df['Book'] != 1984]
df

                    Book           Author  Price    year    Year
0                   1984    George Orwell    250  1949.0     NaN
1  To Kill a mockingbird       Harper Lee    300  1960.0     NaN
2      The great gatspby          F.scott    200  1929.0     NaN
3              moby dick  Herman Melville    350  1851.0     NaN
4    Pride and Prejudice      Jane Austen    200     NaN  1813.0