In [8]:
import numpy as np 
import pandas as pd

In [9]:
data = {
    "ID" : [0,1,2,3,4,5,6,7],
    "Name":["Alice","Bob","Charlie","Diana","Ethon" , "Fiona", "George", "Hannah"],
    "Marks": [91,88,95,76,84,89,73,98],
    "Age": [23,22,24,21,23,22,25,24],
    "Grade":  ["A","B","A","C","B","B","C","A"]
}
df = pd.DataFrame(data)
df.to_json("students.json", index = False)

In [10]:
rd = pd.read_json('students.json')
print(rd)

   ID     Name  Marks  Age Grade
0   0    Alice     91   23     A
1   1      Bob     88   22     B
2   2  Charlie     95   24     A
3   3    Diana     76   21     C
4   4    Ethon     84   23     B
5   5    Fiona     89   22     B
6   6   George     73   25     C
7   7   Hannah     98   24     A

In [11]:
# data cleaning
my_data = pd.DataFrame({
    "Name": ["Alice","Bob","Charlie","David","Eva" , "Frank", "Grace", "Heide"],
    "Score": [85,np.nan,95,70,np.nan,88,95,88],
    "Age": [25,-1,23,22,21,25,np.nan,25],
    "Date" : ['2023-01-01','2023-02-15','not-a-date','2023-03-20','','2023-05-30','2023-05-30','2023-05-30']
})

In [12]:
df = pd.DataFrame(my_data)
df.to_csv("my_data.csv", index = False)

In [13]:

display(df)

      Name  Score   Age        Date
0    Alice   85.0  25.0  2023-01-01
1      Bob    NaN  -1.0  2023-02-15
2  Charlie   95.0  23.0  not-a-date
3    David   70.0  22.0  2023-03-20
4      Eva    NaN  21.0
5    Frank   88.0  25.0  2023-05-30
6    Grace   95.0   NaN  2023-05-30
7    Heide   88.0  25.0  2023-05-30

In [14]:
# removing Rows with empy cells

cleaned_df = df.dropna()
print(cleaned_df.to_string())
print(type(cleaned_df))
print(type(cleaned_df.to_string()))

      Name  Score   Age        Date
0    Alice   85.0  25.0  2023-01-01
2  Charlie   95.0  23.0  not-a-date
3    David   70.0  22.0  2023-03-20
5    Frank   88.0  25.0  2023-05-30
7    Heide   88.0  25.0  2023-05-30
<class 'pandas.core.frame.DataFrame'>
<class 'str'>

In [15]:
# replace nan values
df.fillna(999, inplace = True)
print(df)

      Name  Score    Age        Date
0    Alice   85.0   25.0  2023-01-01
1      Bob  999.0   -1.0  2023-02-15
2  Charlie   95.0   23.0  not-a-date
3    David   70.0   22.0  2023-03-20
4      Eva  999.0   21.0
5    Frank   88.0   25.0  2023-05-30
6    Grace   95.0  999.0  2023-05-30
7    Heide   88.0   25.0  2023-05-30

In [16]:
# replacing column with 999

In [17]:
df = pd.read_csv('my_data.csv')
df.fillna({"Score": 999}, inplace = True)
display(df)

      Name  Score   Age        Date
0    Alice   85.0  25.0  2023-01-01
1      Bob  999.0  -1.0  2023-02-15
2  Charlie   95.0  23.0  not-a-date
3    David   70.0  22.0  2023-03-20
4      Eva  999.0  21.0         NaN
5    Frank   88.0  25.0  2023-05-30
6    Grace   95.0   NaN  2023-05-30
7    Heide   88.0  25.0  2023-05-30

In [ ]:
# replacing column with mean value

In [19]:
df = pd.read_csv('my_data.csv')
mean_value = df["Score"].mean()
df.fillna({"Score": mean_value.round(2)}, inplace = True)
display(df)

      Name  Score   Age        Date
0    Alice  85.00  25.0  2023-01-01
1      Bob  86.83  -1.0  2023-02-15
2  Charlie  95.00  23.0  not-a-date
3    David  70.00  22.0  2023-03-20
4      Eva  86.83  21.0         NaN
5    Frank  88.00  25.0  2023-05-30
6    Grace  95.00   NaN  2023-05-30
7    Heide  88.00  25.0  2023-05-30

In [21]:
# replacing column with median value
df = pd.read_csv('my_data.csv')
median_value = df["Score"].median()
df.fillna({"Score": median_value}, inplace = True)
display(df)

      Name  Score   Age        Date
0    Alice   85.0  25.0  2023-01-01
1      Bob   88.0  -1.0  2023-02-15
2  Charlie   95.0  23.0  not-a-date
3    David   70.0  22.0  2023-03-20
4      Eva   88.0  21.0         NaN
5    Frank   88.0  25.0  2023-05-30
6    Grace   95.0   NaN  2023-05-30
7    Heide   88.0  25.0  2023-05-30

In [22]:
import pandas as pd

df = pd.read_csv('my_data.csv')

# Calculate mode (returns a Series, so take the first value)
mode_value = df["Score"].mode()[0]

# Replace NaN values with mode
df.fillna({"Score": mode_value}, inplace=True)

display(df)

      Name  Score   Age        Date
0    Alice   85.0  25.0  2023-01-01
1      Bob   88.0  -1.0  2023-02-15
2  Charlie   95.0  23.0  not-a-date
3    David   70.0  22.0  2023-03-20
4      Eva   88.0  21.0         NaN
5    Frank   88.0  25.0  2023-05-30
6    Grace   95.0   NaN  2023-05-30
7    Heide   88.0  25.0  2023-05-30